### ISSUE TITLE
Event stream response appears not to work.

### ISSUE THREAD

**Issue by mikeal** [zeit/now-issues#15]
I'm running signalhub on ziet. It's pretty simple: https://github.com/mikeal/signalhub-zeit/blob/master/package.json

Running locally I get the response headers just fine, but on ziet I never get the headers flushed. Signal hub uses a simple event source stream for signaling.

Here's localhost:

```
% curl http://localhost/v1/test/all --verbose                                                   
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET /v1/test/all HTTP/1.1
> Host: localhost
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Headers: X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept, Authorization
< Content-Type: text/event-stream; charset=utf-8
< Date: Sat, 06 Aug 2016 23:25:28 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
```

And here's the service on zeit.

```
% curl https://signalhub-zeit-wmngywitfw.now.sh/v1/test/all --verbose               
*   Trying 52.52.4.74...
* Connected to signalhub-zeit-wmngywitfw.now.sh (52.52.4.74) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.now.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /v1/test/all HTTP/1.1
> Host: signalhub-zeit-wmngywitfw.now.sh
> User-Agent: curl/7.43.0
> Accept: */*
> 
```

And then it just sites forever :(

**Comment by jamox** [comment]
Hey, I just tried this out (out of curiosity) and it seemed to work for me; I just deployed the repo you linked. Output of `$ curl -v  https://signalhub-zeit-danepyujhu.now.sh/` below in details
<details>
```
*   Trying 54.183.106.65...
* Connected to signalhub-zeit-danepyujhu.now.sh (54.183.106.65) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.now.sh
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET / HTTP/1.1
> Host: signalhub-zeit-danepyujhu.now.sh
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 11 Aug 2016 13:35:09 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, PUT, DELETE
< Access-Control-Allow-Credentials: true
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Headers: X-Requested-With, X-HTTP-Method-Override, Content-Type, Accept, Authorization
< Strict-Transport-Security: max-age=31536000; includeSubDomains;
<
{
  "name": "signalhub",
  "version": "4.7.4",
  "subscribers": 0
}
* Connection #0 to host signalhub-zeit-danepyujhu.now.sh left intact
```
</details>

**Comment by mikeal** [comment]
The root path is a different resource, that always works, it's only the `/v1/*` resources that are event source responses.

**Comment by remy** [comment]
@mikeal bit of an old issue, and I don't have any more information than you do, but have you tried pushing an initial payload upon connection? It _could_ be that there's buffering going on at Zeit's level. Similarly to how servers won't send the body until 2K (or something) has been sent.

Of course, you shouldn't need to for `event-stream` but it might be worth a try as a debug?

**Comment by mikeal** [comment]
I'm willing to bet the payload is less than 2K. While this is a common service (signalhub) that a lot of other people are using I'm actually not using it anymore and am using "signal exchange" which uses socket.io and is running fine, so even tho this is still an issue you can go ahead and close it if you're just worried about me :)

**Comment by leo** [comment]
https://github.com/zeit/now/issues/20
